name: Build and Publish Release

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  security-events: write
  id-token: write  # Needed for creating release and uploading assets

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: List target contents
        run: ls -la target

      # Create a Git tag
      - name: Create Tag
        id: tag
        run: |
          TAG="v1.0.0"
          git tag $TAG
          git push origin $TAG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Create Release and Upload Asset
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          files: |
            target/CafeteriaManagerSystem-Backend-1.0-SNAPSHOT.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
