name: Build and Publish Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  security-events: write
  id-token: write  # Needed for creating release and uploading assets

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: List target contents
        run: ls -la target

      # Update the dependency graph before uploading artifacts
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@v4

      # Create a GitHub Release (only if it doesn't already exist)
      - name: Create Release
        id: create_release
        uses: gh actions/create-release@v1
        with:
          tag_name: "v1.0.0"  # Adjust version number as necessary
          release_name: "Release 1.0.0"
          body: "Release of CafeteriaManagerSystem-Backend-1.0-SNAPSHOT"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Upload the JAR to the release
      - name: Upload JAR to Release
        uses: gh actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/CafeteriaManagerSystem-Backend-1.0-SNAPSHOT.jar
          asset_name: CafeteriaManagerSystem-Backend-1.0-SNAPSHOT.jar
          asset_content_type: application/java-archive
