name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: List target contents
        run: ls -la target

      # Upload only the specified JAR (CafeteriaManagerSystem-Backend-1.0-SNAPSHOT.jar)
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: CafeteriaManagerSystem-Backend-1.0-SNAPSHOT
          path: target/CafeteriaManagerSystem-Backend-1.0-SNAPSHOT.jar

      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@v4
