name: BACKEND-SERVER

on:
  workflow_dispatch:  # Manual trigger
  release:
    types: [published]  # Auto-run on release

jobs:
  run-java-backend:
    name: Run CafeteriaManagerSystem Java Backend
    runs-on: self-hosted
    timeout-minutes: 1440

    env:
      NGROK_AUTHTOKEN: ${{ secrets.NGROK_AUTHTOKEN }}
      NGROK_DOMAIN: ${{ secrets.NGROK_DOMAIN }}

    steps:
      - name: Set up app directory
        run: mkdir -p app

      - name: Download JAR file
        working-directory: ./app
        run: |
          curl -L -o CafeteriaManagerSystem.jar https://github.com/NgDinhKhiem/CafeteriaManagerSystem-Backend/releases/download/v1.0.0/CafeteriaManagementSystem.jar

      - name: Start Java Backend
        working-directory: ./app
        run: |
          nohup java -Xmx512M -Xms256M -jar CafeteriaManagerSystem.jar > backend-java.log 2>&1 &

      - name: Wait for Java server to start
        run: sleep 5

      - name: Stream Java backend logs
        run: |
          echo "Streaming Java backend logs..."
          timeout 86400 tail -f app/backend-java.log | tee java-live.log
